version: "3.8"

services:
  app:
    build: .
    container_name: node_app
    restart: always
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://root:example@mongo:27017/mindpocketDB?authSource=admin
      JWT_SECRET: 3bfa5b4fe58f21fde9d43271f711ed15
      BaseURL: http://localhost:3000/share/
      NODE_ENV: production

    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mindpocket-backend

  mongo:
    image: mongo:7
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mindpocketDB
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mindpocket-backend

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - mindpocket-backend

volumes:
  mongo_data:

networks:
  mindpocket-backend:
    driver: bridge