apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: mindpocket-backend
data:
  nginx.conf: |
    events {}

    http {
        upstream node_app {
            # Use the backend service name and port
            server mindpocket-backend-app:3000;
        }

        server {
            listen 80;

            location / {
                proxy_pass http://node_app;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
            }
        }
    }
