apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: mindpocket-backend
data:
  nginx.conf: |
    # Your custom NGINX configuration here
    server {
      listen 80;
      location / {
            proxy_pass http://node_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
