name: Build & Deploy to EC2 Kubernetes

on:
  pull_request:
    types: [closed]
    branches:
      - development
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 1.1: Refresh code to ensure latest changes
      - name: Refresh Code
        run: |
          git pull origin ${GITHUB_REF_NAME}

      # Step 2: Log in to Docker Hub using PAT
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t shashikdocker/mindpocket-backend:${GITHUB_SHA} .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push shashikdocker/mindpocket-backend:${GITHUB_SHA}

      # Step 5: SSH into EC2 and deploy to k3s
      - name: SSH into EC2 and Deploy to k3s
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export KUBECONFIG=$HOME/.kube/config
            # If deployment exists, update image; else apply YAMLs
            kubectl set image deployment/mindpocket-backend mindpocket-backend=shashikdocker/mindpocket-backend:${GITHUB_SHA} || \
            kubectl apply -f ~/projects/mindpocket-backend/k8s
