name: Build & Deploy to EC2 Kubernetes

on:
  pull_request:
    types: [closed]
    branches:
      - development
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Refresh Code
        run: |
          git pull origin ${GITHUB_REF_NAME}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build Docker Image
        run: |
          docker build -t shashikdocker/mindpocket-backend:${GITHUB_SHA} .

      - name: Push Docker Image
        run: |
          docker push shashikdocker/mindpocket-backend:${GITHUB_SHA}

      - name: Copy Kubernetes Manifests to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "k8s/*.yaml"
          target: "~/projects/mindpocket-backend/"
          strip_components: 1

      - name: SSH into EC2 and Deploy to k3s
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export KUBECONFIG=$HOME/.kube/config
            # If deployment exists, update image; else apply YAMLs
            kubectl set image deployment/mindpocket-backend-app mindpocket-backend-app=shashikdocker/mindpocket-backend:${GITHUB_SHA} || \
            kubectl apply -f ~/projects/mindpocket-backend/
